# Generated by Django 4.2 on 2024-01-13 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('video_file', models.FileField(upload_to='uploaded_video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('uploaded_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
