# Generated by Django 4.2 on 2024-01-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_uploadedvideo_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideo',
            name='video_image',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphoto%2Fpopcorn-in-bucket-gm497857462-79351717&psig=AOvVaw2eKWQMD-S2_JzS7w0KoJw4&ust=1705173460818000&source=images&cd=vfe&ved=0CBMQjRxqFwoTCPiHuMfi2YMDFQAAAAAdAAAAABAE'),
        ),
    ]
