# Generated by Django 4.2 on 2024-01-13 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_uploadedvideo_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideo',
            name='uploaded_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
