# Generated by Django 4.2 on 2024-01-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_uploadedvideo_uploaded_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.uploadedvideo')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='joined_room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.room'),
        ),
    ]
