# Generated by Django 4.2 on 2024-01-13 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_room_user_joined_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.room'),
        ),
    ]
