# Generated by Django 4.2 on 2024-01-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_user_joined_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_room',
        ),
    ]
