# Generated by Django 4.2 on 2024-01-13 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_user_joined_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.room'),
        ),
    ]
