# Generated by Django 4.2 on 2024-01-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_user_alter_room_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_room',
        ),
    ]
