# Generated by Django 4.2 on 2024-01-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_user_joined_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
