# Generated by Django 4.2 on 2024-01-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_in_room',
            field=models.IntegerField(default=0),
        ),
    ]
