# Generated by Django 4.2 on 2024-01-13 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_room_user_in_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_dynamic_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.room')),
                ('user_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
            ],
        ),
    ]
