# Generated by Django 4.2 on 2024-01-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_userdynamicfield_user_dynamic_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inter_room_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserDynamicField',
        ),
    ]
